# Status
STATUS_PENDING = 'P'
STATUS_ACCEPT = 'A'
STATUS_REJECT = 'R'
STATUS_CONFIRMED = 'C'
STATUS_VALID = 'V'

# Protocols
PROTOCOL_HTTPS = 'H'
PROTOCOL_RSYNC = 'R'

# Bag Types
BAGTYPE_DATA = 'D'
BAGTYPE_RIGHTS = 'R'
BAGTYPE_BRIGHTENING = 'B'

# Fixity
FIXITY_SHA256 = 'sha256'
