# Status
STATUS_ACCEPTED  = 'Accepted'
STATUS_CONFIRMED = 'Confirmed'
STATUS_CANCELLED = 'Cancelled'
STATUS_FINISHED  = 'Finished'
STATUS_PREPARED  = 'Prepared'
STATUS_REQUESTED = 'Requested'
STATUS_REJECTED  = 'Rejected'
STATUS_RECEIVED  = 'Received'

STATUSES = (STATUS_ACCEPTED, STATUS_CONFIRMED, STATUS_CANCELLED,
            STATUS_FINISHED, STATUS_PREPARED, STATUS_REQUESTED,
            STATUS_REJECTED, STATUS_RECEIVED)


# Protocols
PROTOCOL_HTTPS = 'H'
PROTOCOL_RSYNC = 'R'

PROTOCOLS = (PROTOCOL_HTTPS, PROTOCOL_RSYNC)

# Bag Types
BAGTYPE_DATA = 'D'
BAGTYPE_RIGHTS = 'R'
BAGTYPE_BRIGHTENING = 'B'

BAG_TYPES = (BAGTYPE_DATA, BAGTYPE_RIGHTS, BAGTYPE_BRIGHTENING)

# Fixity
FIXITY_SHA256 = 'sha256'

FIXITY_TYPES = (FIXITY_SHA256)
