# Status
STATUS_PENDING = 'P'
STATUS_ACCEPT = 'A'
STATUS_REJECT = 'R'
STATUS_CONFIRMED = 'C'
STATUS_VALID = 'V'

STATUSES = (STATUS_PENDING, STATUS_ACCEPT, STATUS_REJECT, STATUS_CONFIRMED, STATUS_VALID)

# Protocols
PROTOCOL_HTTPS = 'H'
PROTOCOL_RSYNC = 'R'

PROTOCOLS = (PROTOCOL_HTTPS, PROTOCOL_RSYNC)

# Bag Types
BAGTYPE_DATA = 'D'
BAGTYPE_RIGHTS = 'R'
BAGTYPE_BRIGHTENING = 'B'

BAG_TYPES = (BAGTYPE_DATA, BAGTYPE_RIGHTS, BAGTYPE_BRIGHTENING)

# Fixity
FIXITY_SHA256 = 'sha256'

FIXITY_TYPES = (FIXITY_SHA256)
